//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMS.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class Employee
    {
        public enum Privilege
        {
            User, Admin
        }

        public int id { get; set; }
        public string firstName { get; set; }
        public string lastName { get; set; }
        public int phoneNo { get; set; }
        public string homeAddress { get; set; }
        public string email { get; set; }
        public System.DateTime dob { get; set; }
        public string jobTitle { get; set; }
        public Privilege privilege { get; set; }
        public string password { get; set; }

        [StringLength(450)]
        [Index(IsUnique=true)]
        public string username { get; set; }

        public virtual ICollection<DayOff> DayOffs { get; set; }
        public virtual ICollection<Leave> Leaves { get; set; }
        public virtual ICollection<Shift> Shifts { get; set; }
    }
}
