//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Leave
    {
        public enum LeaveStatus
        {
            Pending, Granted, Refused
        }
        public int id { get; set; }
        public System.DateTime startDate { get; set; }
        public System.DateTime endDate { get; set; }
        public LeaveStatus status { get; set; }
        public int employeeId { get; set; }
    
        public virtual Employee Employee { get; set; }
    }
}
