//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Shift
    {
        public enum Attendance
        {
            Pending, Present, Absent
        }
        public int id { get; set; }
        public System.DateTime date { get; set; }
        public Attendance attendance { get; set; }
        public int employeeId { get; set; }
    
        public virtual Employee Employee { get; set; }
    }
}
